import type {
  User,
  InstagramAccount,
  Automation,
  DmTemplate,
  Message,
  Conversation,
  Comment,
  Notification,
  ActivityLog,
  Subscription,
  Invoice,
  AnalyticsData,
  DashboardStats,
  SupportTicket,
} from "@/types";

export const MOCK_USER: User = {
  id: "usr_01",
  name: "Alex Johnson",
  email: "alex@example.com",
  avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Alex",
  role: "user",
  plan: "professional",
  createdAt: "2024-01-15T10:00:00Z",
  instagramAccounts: 2,
};

export const MOCK_ADMIN_USER: User = {
  id: "usr_admin",
  name: "Admin User",
  email: "admin@dmdost.com",
  avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Admin",
  role: "admin",
  plan: "enterprise",
  createdAt: "2023-12-01T10:00:00Z",
  instagramAccounts: 5,
};

export const MOCK_INSTAGRAM_ACCOUNTS: InstagramAccount[] = [
  {
    id: "ig_01",
    username: "alexjohnson_official",
    displayName: "Alex Johnson",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=ig1",
    followers: 12400,
    following: 892,
    posts: 234,
    isConnected: true,
    tokenStatus: "valid",
    connectedAt: "2024-01-20T10:00:00Z",
    permissions: ["instagram_basic", "instagram_manage_messages", "instagram_manage_comments"],
  },
  {
    id: "ig_02",
    username: "brand_store_official",
    displayName: "Brand Store",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=ig2",
    followers: 45200,
    following: 312,
    posts: 567,
    isConnected: true,
    tokenStatus: "valid",
    connectedAt: "2024-02-05T10:00:00Z",
    permissions: ["instagram_basic", "instagram_manage_messages", "instagram_manage_comments"],
  },
  {
    id: "ig_03",
    username: "personal_blog_xyz",
    displayName: "Personal Blog",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=ig3",
    followers: 3100,
    following: 1200,
    posts: 89,
    isConnected: false,
    tokenStatus: "expired",
    connectedAt: "2023-11-10T10:00:00Z",
    permissions: [],
  },
];

export const MOCK_AUTOMATIONS: Automation[] = [
  {
    id: "auto_01",
    name: "Welcome DM Campaign",
    type: "welcome_dm",
    status: "active",
    trigger: "new_follower",
    conditions: [{ field: "follower_count", operator: "gte", value: "100" }],
    template: "tpl_01",
    delay: 5,
    accountId: "ig_01",
    createdAt: "2024-02-01T10:00:00Z",
    updatedAt: "2024-03-10T10:00:00Z",
    stats: { triggered: 1240, sent: 1198, failed: 42 },
  },
  {
    id: "auto_02",
    name: "Keyword DM - Promo Code",
    type: "keyword_dm",
    status: "active",
    trigger: "comment_keyword",
    conditions: [{ field: "keyword", operator: "contains", value: "discount" }],
    template: "tpl_02",
    delay: 0,
    accountId: "ig_01",
    createdAt: "2024-02-10T10:00:00Z",
    updatedAt: "2024-03-12T10:00:00Z",
    stats: { triggered: 560, sent: 547, failed: 13 },
  },
  {
    id: "auto_03",
    name: "Comment Reply Bot",
    type: "comment_reply",
    status: "active",
    trigger: "comment_on_post",
    conditions: [],
    template: "tpl_03",
    delay: 2,
    accountId: "ig_02",
    createdAt: "2024-02-15T10:00:00Z",
    updatedAt: "2024-03-11T10:00:00Z",
    stats: { triggered: 2340, sent: 2290, failed: 50 },
  },
  {
    id: "auto_04",
    name: "Story Reply Handler",
    type: "story_reply",
    status: "paused",
    trigger: "story_reply",
    conditions: [],
    template: "tpl_04",
    delay: 1,
    accountId: "ig_02",
    createdAt: "2024-03-01T10:00:00Z",
    updatedAt: "2024-03-08T10:00:00Z",
    stats: { triggered: 320, sent: 310, failed: 10 },
  },
  {
    id: "auto_05",
    name: "Follow Check Reward",
    type: "follow_check",
    status: "inactive",
    trigger: "mention",
    conditions: [{ field: "is_follower", operator: "eq", value: "true" }],
    template: "tpl_05",
    delay: 0,
    accountId: "ig_01",
    createdAt: "2024-03-05T10:00:00Z",
    updatedAt: "2024-03-05T10:00:00Z",
    stats: { triggered: 0, sent: 0, failed: 0 },
  },
];

export const MOCK_TEMPLATES: DmTemplate[] = [
  {
    id: "tpl_01",
    name: "Welcome New Follower",
    content: "Hey {{name}}! 👋 Thanks for following {{account}}! We're thrilled to have you. Stay tuned for exclusive content and special offers just for our followers! 🎉",
    variables: ["name", "account"],
    type: "dm",
    createdAt: "2024-02-01T10:00:00Z",
    updatedAt: "2024-03-10T10:00:00Z",
  },
  {
    id: "tpl_02",
    name: "Promo Code DM",
    content: "Hi {{name}}! 🎁 You asked about our discount — here's your exclusive promo code: SAVE20. Use it to get 20% off your next purchase! Valid for 48 hours only. Shop now: {{link}}",
    variables: ["name", "link"],
    type: "dm",
    createdAt: "2024-02-10T10:00:00Z",
    updatedAt: "2024-03-12T10:00:00Z",
  },
  {
    id: "tpl_03",
    name: "Comment Thank You",
    content: "Thank you for your comment, {{name}}! 💜 We love hearing from our community. Feel free to DM us if you have any questions!",
    variables: ["name"],
    type: "comment",
    createdAt: "2024-02-15T10:00:00Z",
    updatedAt: "2024-03-11T10:00:00Z",
  },
  {
    id: "tpl_04",
    name: "Story Reply Response",
    content: "Thanks for your reply on our story, {{name}}! 😊 We noticed you're interested in {{topic}}. Would you like more information? Just send us a DM!",
    variables: ["name", "topic"],
    type: "dm",
    createdAt: "2024-03-01T10:00:00Z",
    updatedAt: "2024-03-08T10:00:00Z",
  },
  {
    id: "tpl_05",
    name: "Follow Reward",
    content: "🌟 You're officially part of our inner circle, {{name}}! As a follower, you get access to our exclusive rewards. Here's your special gift: {{gift_link}}",
    variables: ["name", "gift_link"],
    type: "dm",
    createdAt: "2024-03-05T10:00:00Z",
    updatedAt: "2024-03-05T10:00:00Z",
  },
];

export const MOCK_CONVERSATIONS: Conversation[] = [
  {
    id: "conv_01",
    participant: { id: "p1", name: "Sarah Williams", username: "sarah_w", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=s1" },
    lastMessage: "Thank you so much! The promo code worked perfectly 🙌",
    lastMessageTime: "2024-03-15T14:30:00Z",
    unreadCount: 0,
    accountId: "ig_01",
  },
  {
    id: "conv_02",
    participant: { id: "p2", name: "Marcus Chen", username: "marcuschen", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=m2" },
    lastMessage: "Hey, can I ask about the product?",
    lastMessageTime: "2024-03-15T13:10:00Z",
    unreadCount: 2,
    accountId: "ig_01",
  },
  {
    id: "conv_03",
    participant: { id: "p3", name: "Emily Rodriguez", username: "emilyr", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=e3" },
    lastMessage: "Love your content! Just followed 💜",
    lastMessageTime: "2024-03-15T11:45:00Z",
    unreadCount: 1,
    accountId: "ig_02",
  },
  {
    id: "conv_04",
    participant: { id: "p4", name: "James Wilson", username: "jameswilson", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=j4" },
    lastMessage: "Is there a discount for bulk orders?",
    lastMessageTime: "2024-03-15T10:20:00Z",
    unreadCount: 0,
    accountId: "ig_02",
  },
  {
    id: "conv_05",
    participant: { id: "p5", name: "Aisha Patel", username: "aishap", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=a5" },
    lastMessage: "When will the new collection drop?",
    lastMessageTime: "2024-03-14T16:00:00Z",
    unreadCount: 3,
    accountId: "ig_01",
  },
];

export const MOCK_MESSAGES: Message[] = [
  {
    id: "msg_01",
    conversationId: "conv_01",
    senderId: "p1",
    senderName: "Sarah Williams",
    senderAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=s1",
    content: "Hi! I saw your post about the discount. Can you share the code?",
    timestamp: "2024-03-15T14:20:00Z",
    isRead: true,
    isAutomated: false,
  },
  {
    id: "msg_02",
    conversationId: "conv_01",
    senderId: "ig_01",
    senderName: "alexjohnson_official",
    senderAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=ig1",
    content: "Hi Sarah! 🎁 You asked about our discount — here's your exclusive promo code: SAVE20. Use it to get 20% off your next purchase!",
    timestamp: "2024-03-15T14:21:00Z",
    isRead: true,
    isAutomated: true,
  },
  {
    id: "msg_03",
    conversationId: "conv_01",
    senderId: "p1",
    senderName: "Sarah Williams",
    senderAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=s1",
    content: "Thank you so much! The promo code worked perfectly 🙌",
    timestamp: "2024-03-15T14:30:00Z",
    isRead: true,
    isAutomated: false,
  },
];

export const MOCK_COMMENTS: Comment[] = [
  {
    id: "cmt_01",
    postId: "post_01",
    author: "user_fan123",
    authorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=fan1",
    content: "Love this! Can I get a discount code? 🙏",
    timestamp: "2024-03-15T12:00:00Z",
    replyStatus: "replied",
    matchedKeyword: "discount",
    automationId: "auto_02",
  },
  {
    id: "cmt_02",
    postId: "post_01",
    author: "techguru_99",
    authorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=tg2",
    content: "Amazing product! 🔥",
    timestamp: "2024-03-15T11:30:00Z",
    replyStatus: "replied",
    automationId: "auto_03",
  },
  {
    id: "cmt_03",
    postId: "post_02",
    author: "shopaholic_life",
    authorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=sh3",
    content: "When is the new collection coming? I need it!",
    timestamp: "2024-03-15T10:15:00Z",
    replyStatus: "pending",
  },
  {
    id: "cmt_04",
    postId: "post_02",
    author: "real_photography",
    authorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=rp4",
    content: "Beautiful photo! What camera do you use?",
    timestamp: "2024-03-14T20:45:00Z",
    replyStatus: "ignored",
  },
  {
    id: "cmt_05",
    postId: "post_03",
    author: "fitness_queen_x",
    authorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=fq5",
    content: "I want the discount too! Promo please 💜",
    timestamp: "2024-03-14T18:00:00Z",
    replyStatus: "replied",
    matchedKeyword: "promo",
    automationId: "auto_02",
  },
];

export const MOCK_NOTIFICATIONS: Notification[] = [
  {
    id: "notif_01",
    type: "success",
    title: "Automation Triggered",
    message: "Welcome DM Campaign sent to 12 new followers",
    timestamp: "2024-03-15T15:00:00Z",
    isRead: false,
    link: "/dashboard/automations/auto_01",
  },
  {
    id: "notif_02",
    type: "warning",
    title: "Token Expiring Soon",
    message: "Instagram token for personal_blog_xyz expires in 3 days",
    timestamp: "2024-03-15T12:00:00Z",
    isRead: false,
    link: "/dashboard/instagram",
  },
  {
    id: "notif_03",
    type: "info",
    title: "New Messages",
    message: "You have 6 unread messages across your accounts",
    timestamp: "2024-03-15T10:30:00Z",
    isRead: true,
    link: "/dashboard/messages",
  },
  {
    id: "notif_04",
    type: "success",
    title: "Subscription Renewed",
    message: "Your Professional plan has been renewed successfully",
    timestamp: "2024-03-14T09:00:00Z",
    isRead: true,
  },
  {
    id: "notif_05",
    type: "error",
    title: "Automation Failed",
    message: "Story Reply Handler failed to send 3 messages",
    timestamp: "2024-03-13T16:45:00Z",
    isRead: true,
    link: "/dashboard/automations/auto_04",
  },
];

export const MOCK_ACTIVITY_LOGS: ActivityLog[] = [
  {
    id: "log_01",
    type: "automation_triggered",
    description: "Welcome DM Campaign triggered for @new_user_123",
    timestamp: "2024-03-15T15:00:00Z",
    status: "success",
    metadata: { automation: "Welcome DM Campaign", user: "@new_user_123" },
  },
  {
    id: "log_02",
    type: "dm_sent",
    description: "Automated DM sent to @sarah_williams",
    timestamp: "2024-03-15T14:21:00Z",
    status: "success",
    metadata: { recipient: "@sarah_williams", template: "Promo Code DM" },
  },
  {
    id: "log_03",
    type: "comment_replied",
    description: "Auto-reply posted on post_01 comment",
    timestamp: "2024-03-15T12:05:00Z",
    status: "success",
    metadata: { post: "post_01", keyword: "discount" },
  },
  {
    id: "log_04",
    type: "login",
    description: "User logged in from Chrome on macOS",
    timestamp: "2024-03-15T09:00:00Z",
    status: "success",
    metadata: { browser: "Chrome", os: "macOS" },
  },
  {
    id: "log_05",
    type: "automation_created",
    description: "New automation 'Follow Check Reward' created",
    timestamp: "2024-03-05T10:00:00Z",
    status: "success",
    metadata: { automation: "Follow Check Reward" },
  },
  {
    id: "log_06",
    type: "dm_failed",
    description: "Failed to send DM to @user_blocked - user has DMs restricted",
    timestamp: "2024-03-04T17:30:00Z",
    status: "failed",
    metadata: { recipient: "@user_blocked", reason: "DMs restricted" },
  },
  {
    id: "log_07",
    type: "subscription_updated",
    description: "Subscription upgraded from Starter to Professional",
    timestamp: "2024-03-01T11:00:00Z",
    status: "success",
    metadata: { from: "starter", to: "professional" },
  },
];

export const MOCK_SUBSCRIPTION: Subscription = {
  id: "sub_01",
  plan: "professional",
  status: "active",
  currentPeriodStart: "2024-03-01T00:00:00Z",
  currentPeriodEnd: "2024-04-01T00:00:00Z",
  cancelAtPeriodEnd: false,
  usage: {
    automations: { used: 5, limit: 20 },
    messages: { used: 4235, limit: 10000 },
    accounts: { used: 2, limit: 5 },
  },
};

export const MOCK_INVOICES: Invoice[] = [
  {
    id: "inv_01",
    amount: 4900,
    currency: "USD",
    status: "paid",
    date: "2024-03-01T00:00:00Z",
    description: "Professional Plan - March 2024",
    pdfUrl: "#",
  },
  {
    id: "inv_02",
    amount: 4900,
    currency: "USD",
    status: "paid",
    date: "2024-02-01T00:00:00Z",
    description: "Professional Plan - February 2024",
    pdfUrl: "#",
  },
  {
    id: "inv_03",
    amount: 1900,
    currency: "USD",
    status: "paid",
    date: "2024-01-01T00:00:00Z",
    description: "Starter Plan - January 2024",
    pdfUrl: "#",
  },
];

export const MOCK_ANALYTICS: AnalyticsData[] = [
  { date: "Mar 01", messagesSent: 120, commentsReplied: 45, followersGained: 23, automationsTriggered: 180 },
  { date: "Mar 02", messagesSent: 145, commentsReplied: 62, followersGained: 31, automationsTriggered: 220 },
  { date: "Mar 03", messagesSent: 98, commentsReplied: 38, followersGained: 15, automationsTriggered: 145 },
  { date: "Mar 04", messagesSent: 165, commentsReplied: 71, followersGained: 42, automationsTriggered: 260 },
  { date: "Mar 05", messagesSent: 189, commentsReplied: 84, followersGained: 56, automationsTriggered: 295 },
  { date: "Mar 06", messagesSent: 134, commentsReplied: 55, followersGained: 28, automationsTriggered: 200 },
  { date: "Mar 07", messagesSent: 210, commentsReplied: 92, followersGained: 67, automationsTriggered: 320 },
  { date: "Mar 08", messagesSent: 178, commentsReplied: 74, followersGained: 45, automationsTriggered: 270 },
  { date: "Mar 09", messagesSent: 230, commentsReplied: 95, followersGained: 78, automationsTriggered: 345 },
  { date: "Mar 10", messagesSent: 195, commentsReplied: 83, followersGained: 52, automationsTriggered: 298 },
  { date: "Mar 11", messagesSent: 142, commentsReplied: 58, followersGained: 34, automationsTriggered: 212 },
  { date: "Mar 12", messagesSent: 267, commentsReplied: 112, followersGained: 89, automationsTriggered: 398 },
  { date: "Mar 13", messagesSent: 310, commentsReplied: 134, followersGained: 102, automationsTriggered: 460 },
  { date: "Mar 14", messagesSent: 289, commentsReplied: 121, followersGained: 94, automationsTriggered: 430 },
  { date: "Mar 15", messagesSent: 324, commentsReplied: 145, followersGained: 118, automationsTriggered: 482 },
];

export const MOCK_DASHBOARD_STATS: DashboardStats = {
  totalAutomations: 5,
  activeAutomations: 3,
  messagesSent: 4235,
  commentsReplied: 2290,
  followersGained: 874,
  connectedAccounts: 2,
  successRate: 96.8,
  monthlyUsage: 42.35,
};

export const MOCK_SUPPORT_TICKETS: SupportTicket[] = [
  {
    id: "tkt_01",
    subject: "Automation not triggering for new followers",
    status: "resolved",
    priority: "high",
    createdAt: "2024-03-10T10:00:00Z",
    updatedAt: "2024-03-12T14:00:00Z",
    userId: "usr_01",
    userName: "Alex Johnson",
  },
  {
    id: "tkt_02",
    subject: "Instagram token expired and won't reconnect",
    status: "in_progress",
    priority: "medium",
    createdAt: "2024-03-14T09:00:00Z",
    updatedAt: "2024-03-15T11:00:00Z",
    userId: "usr_01",
    userName: "Alex Johnson",
  },
  {
    id: "tkt_03",
    subject: "Billing question about annual subscription",
    status: "open",
    priority: "low",
    createdAt: "2024-03-15T08:00:00Z",
    updatedAt: "2024-03-15T08:00:00Z",
    userId: "usr_01",
    userName: "Alex Johnson",
  },
];
